services:
  navistats:
    container_name: navistats
    image: ghcr.io/zortexsenpai/navistats:latest
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json:ro

    # Add these labels if you plan to use Traefik as the reverse proxy:
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.navistats.rule=Host(`navistats.example.com`)"
    #  - "traefik.http.routers.navistats.entrypoints=websecure"
    #  - "traefik.http.routers.navistats.tls.certresolver=letsencrypt"
    #  - "traefik.http.services.navistats.loadbalancer.server.port=80"
    #networks:
    #  - frontend

#networks:
#  frontend:
#    external: true
